/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BbsList: typeof import('./components/previews/bbs-list.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    LogListEditorItem: typeof import('./components/LogListEditorItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OptionView: typeof import('./components/OptionView.vue')['default']
    PreviewBbs: typeof import('./components/previews/preview-bbs.vue')['default']
    PreviewBbsItem: typeof import('./components/previews/preview-bbs-item.vue')['default']
    PreviewBbsPineapple: typeof import('./components/previews/preview-bbs-pineapple.vue')['default']
    PreviewBbsPineappleItem: typeof import('./components/previews/preview-bbs-pineapple-item.vue')['default']
    PreviewBubble: typeof import('./components/previews/preview-bubble.vue')['default']
    PreviewBubbleItem: typeof import('./components/previews/preview-bubble-item.vue')['default']
    PreviewBubbleItemCopy: typeof import('./components/previews/preview-bubble-item-copy.vue')['default']
    PreviewMain: typeof import('./components/previews/preview-main.vue')['default']
    PreviewMainItem: typeof import('./components/previews/preview-main-item.vue')['default']
    PreviewMainItemNoavatar: typeof import('./components/previews/preview-main-item-noavatar.vue')['default']
    PreviewMainNoavatar: typeof import('./components/previews/preview-main-noavatar.vue')['default']
    PreviewTableTr: typeof import('./components/previews/preview-table-tr.vue')['default']
    PreviewTableTrNoavatar: typeof import('./components/previews/preview-table-tr-noavatar.vue')['default']
    PreviewTrg: typeof import('./components/previews/preview-trg.vue')['default']
    PreviewTrgItem: typeof import('./components/previews/preview-trg-item.vue')['default']
  }
}
